version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cache"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/charmer"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/http"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/set"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/slackbot"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/tabulator"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/taskmanager"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/testutils"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
