version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/cache"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/charmer"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/httputils"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/pubsub"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/set"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/testutils"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
