name: Release

on:
  push:
    tags:
      - 'cache/v*'
      - 'httpclient/v*'
      - 'httpserver/v*'
      - 'set/v*'
      - 'slackbot/v*'
      - 'tabulator/v*'
      - 'taskmanager/v*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.21'
          - '1.22'
        module:
          - cache
          - httpclient
          - httpserver
          - set
          - slackbot
          - tabulator
          - taskmanager
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: ${{ matrix.module }}/go.sum
      - name: test
        run: |
          cd ${{ matrix.module }}
          go vet ./...
          go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v4
        if: matrix.go-version == '1.21'
        with:
          file: ${{ matrix.module}}/coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
